name: example
description: example for this dart API
version: 0.0.2
author: Alexander Schacht <grumpf@gmx.de>
homepage: https://github.com/Grumpf86/openfoodfacts-dart

environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'

dependencies:
  openfoodfacts: 0.3.15+2

dev_dependencies:
  test: any
