version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/src/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directories:
      - "/src/java/infra"
      - "/src/nodejs/infra"
    schedule:
      interval: "weekly"