version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/src/java"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directories:
      - "/src/nodejs"
      - "/src/rust"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/src/dotnet"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directories:
      - "/src/java/infra"
      - "/src/nodejs/infra"
      - "/src/dotnet/infra"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directories:
      - "/src/rust"
    schedule:
      interval: "monthly"
