require:
  - rubocop-rubycw
  - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: true
  Exclude:
    - 'vendor/bundle/**/*'
Rubycw/Rubycw:
  Enabled: true
  Exclude:
    - 'test/**/*_test.rb'

RBS:
  Enabled: true
RBS/Layout:
  Enabled: true
  Exclude:
    - 'sig/**/*'
    - 'test/**/*'
RBS/Layout/CommentIndentation:
  Exclude:
    - core/string.rbs
RBS/Lint:
  Enabled: true
  Exclude:
    - 'sig/**/*'
    - 'test/**/*'
RBS/Style:
  Enabled: false
  Exclude:
    - 'sig/**/*'
    - 'test/**/*'

Lint/DuplicateMethods:
  Enabled: true
  Include:
    - 'test/**/*_test.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  Include:
    - 'lib/**/*.rb'
