language: go

services:
  - docker

go:
  - "1.11"
  - "stable"

before_install:
  - docker-compose up -d

install:
  - mkdir -p $GOPATH/bin

script:
  - make all

after_script:
  - docker-compose down -v
