include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    omit_local_variable_types: ignore
    annotate_overrides: ignore
    use_function_type_syntax_for_parameters: ignore
