[package]
name = "aries-store-kv"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "Hyperledger Aries key-value storage interface"
license = "MIT/Apache-2.0"

[lib]
name = "aries_store_kv"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
logger = ["env_logger", "log"]
default = ["log", "postgres", "sqlite"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
pg_test = []

[dependencies]
async-mutex = "1.1"
async-resource = { version = "0.1", path = "../async-resource-rs/async-resource" }
async-stream = "0.3"
async-trait = "0.1.30"
chrono = "0.4"
env_logger = { version = "0.7.1", optional = true }
futures-util = "0.3"
hex = "0.4"
hmac = "0.7"
indy-utils = { version = "0.3.1", path = "../indy-shared-rs/indy-utils", default-features = false, features = ["serde_support", "wallet_key", "wql"] }
itertools = "0.9"
log = { version = "0.4.8", optional = true }
rmp-serde = "0.14"
rust-argon2 = "0.8"
serde = "1.0"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["chrono", "runtime-async-std", "tls"], path = "../sqlx" }
suspend = { version = "0.1.3", path = "../async-resource-rs/suspend" }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dev-dependencies]
rand = "0.7"
