[package]
name = "aries-store-kv"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "Hyperledger Aries key-value storage interface"
license = "MIT/Apache-2.0"

[lib]
name = "aries_store_kv"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
logger = ["env_logger", "log"]
default = ["log", "sqlite_bundled"]
sqlite = ["r2d2", "r2d2_sqlite", "rusqlite"]
sqlite_bundled = ["sqlite", "rusqlite/bundled"]

[dependencies]
async-trait = "0.1.30"
env_logger = { version = "0.7.1", optional = true }
futures-channel = "0.3"
futures-util = "0.3"
itertools = "0.9"
lazy_static = "1.3.0"
log = { version = "0.4.8", optional = true }
piper = "0.1"
r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.15.0", optional = true }
rusqlite = { version = "0.22.0", optional = true }
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.40"
smol = "0.1.10"
thiserror = "1.0.9"
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dev-dependencies]
rand = "0.7"
