[package]
name = "aries-store-kv"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "Hyperledger Aries key-value storage interface"
license = "MIT/Apache-2.0"

[lib]
name = "aries_store_kv"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
logger = ["env_logger", "log"]
default = ["log", "sqlite_bundled", "postgres"]
postgres = ["postgres-types", "smol", "tokio-postgres", "tokio-util"]
sqlite = ["rusqlite"]
sqlite_bundled = ["sqlite", "rusqlite/bundled"]

[dependencies]
async-channel = "1.1"
async-resource = { version = "0.1", path = "../async-resource-rs/async-resource" }
async-trait = "0.1.30"
env_logger = { version = "0.7.1", optional = true }
futures-util = "0.3"
hex = "0.4"
hmac = "0.7"
indy-utils = { version = "0.3.1", path = "../indy-shared-rs/indy-utils", default-features = false, features = ["serde_support", "wallet_key", "wql"] }
itertools = "0.9"
log = { version = "0.4.8", optional = true }
postgres-types = { version = "0.1", optional = true }
rusqlite = { version = "0.22.0", optional = true }
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.40"
smol = { version = "0.1.10", optional = true }
suspend = { version = "0.1", path = "../async-resource-rs/suspend" }
tokio-postgres = { version = "0.5", default-features = false, optional = true }
tokio-util = { version = "0.3", default-features = false, features = ["compat"], optional = true }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dev-dependencies]
rand = "0.7"
smol = "0.1.10"
