[package]
name = "sigstore"
description = "An experimental crate to interact with sigstore"
version = "0.1.0"
edition = "2018"
authors = [
  "sigstore-rs developers",
]


[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
base64 = "0.13.0"
ecdsa = { version = "0.12.4", features = ["verify", "pem", "der", "pkcs8"] }
oci-distribution = "0.7.0"
olpc-cjson = "0.1.1"
p256 = {version = "0.9.0", features = ["ecdsa-core"]}
serde_json = "1.0.68"
serde = {version = "1.0.130", features = ["derive"]}
tokio = { version = "1.12.0", features = ["full"]}
tracing = "0.1.29"
x509-parser = { version = "0.12.0", features = ["verify"]}

[dev-dependencies]
chrono = "0.4.19"
clap = "2.33.3"
openssl = "0.10.38"
tracing-subscriber = "0.2.25"
