[package]
name = "sigstore"
description = "An experimental crate to interact with sigstore"
version = "0.0.1"
edition = "2018"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
]


[dependencies]
anyhow = "1.0.44"
base64 = "0.13.0"
ecdsa = { version = "0.12.4", features = ["verify", "pem", "der", "pkcs8"] }
oci-distribution = "0.7.0"
p256 = {version = "0.9.0", features = ["ecdsa-core"]}
tokio = { version = "1.12.0", features = ["full"]}
tracing = "0.1.28"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.68"

[dev-dependencies]
clap = "2.33.3"
