[package]
name = "sigstore"
description = "An experimental crate to interact with sigstore"
version = "0.2.0"
edition = "2018"
authors = [
  "sigstore-rs developers",
]

[features]
default = ["native-tls"]
native-tls = ["oci-distribution/native-tls"]
rustls-tls = ["oci-distribution/rustls-tls"]

[dependencies]
async-trait = "0.1.51"
base64 = "0.13.0"
der-parser = "6.0.1"
# TODO: go back to the officially release oci-distribution once these patches are released
oci-distribution = { git = "https://github.com/krustlet/oci-distribution", rev = "0f717968093a5415f428503d741dedf24ea97948", default-features = false }
#oci-distribution = { version = "0.8.1", default-features = false }
olpc-cjson = "0.1.1"
open = "2.0.2"
openidconnect = "2.2.0"
pem = "1.0.2"
reqwest = "0.11.9"
ring = "0.16.20"
serde_json = "1.0.68"
serde = {version = "1.0.130", features = ["derive"]}
sha2 = "0.10.1"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["full"]}
tough = { version = "0.12.1", features = [ "http" ] }
tracing = "0.1.29"
url = "2.2.2"
x509-parser = { version = "0.12.0", features = ["verify"]}

[dev-dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
clap = "2.33.3"
openssl = "0.10.38"
tempfile = "3.3.0"
tracing-subscriber = "0.2.25"