[package]
name = "aries-store-kv"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "Hyperledger Aries key-value storage interface"
license = "MIT/Apache-2.0"

[lib]
name = "aries_store_kv"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]

[features]
default = ["ffi", "log", "postgres", "sqlite"]
ffi = ["ffi-support", "logger"]
logger = ["env_logger", "log"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
pg_test = ["postgres"]

[dependencies]
async-mutex = "1.3"
async-resource = { version = "0.1", path = "../async-resource-rs/async-resource" }
async-stream = "0.3"
async-trait = "0.1.30"
chrono = "0.4"
env_logger = { version = "0.7.1", optional = true }
ffi-support = { version = "0.4.0", optional = true }
futures-util = "0.3"
hex = "0.4"
hmac = "0.7"
indy-utils = { version = "0.3.1", path = "../indy-shared-rs/indy-utils", default-features = false, features = ["serde_support", "wallet_key", "wql"] }
itertools = "0.9"
log = { version = "0.4.8", optional = true }
once_cell = "1.4"
percent-encoding = "2.0"
rmp-serde = "0.14"
rust-argon2 = "0.8"
serde = "1.0"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_json = "1.0"

# should correspond to version imported by sqlx via async-std,
# only used for timer and sleep right now (switch to async-io later)
smol = "0.1"

suspend = { version = "0.1.3", path = "../async-resource-rs/suspend" }
url = { version = "2.1", default-features = false }
uuid = { version = "0.8", features = ["v4"] }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }

[dependencies.sqlx]
git = "https://github.com/launchbadge/sqlx"
rev = "1acd782e7f518857abccaedf7d0c06a4c9389e27"
version = "0.4.0-beta.1"
default-features = false
features = ["chrono", "runtime-async-std", "tls"]


# [target.'cfg(target_os = "macos")'.dependencies]
# keychain-services = { path = "../keychain-services.rs" }
# keychain-services = { git = "https://github.com/iqlusioninc/keychain-services.rs", rev = "7410fb8baf4ecdf04cdcd7d06d02658f4f158d77" }

[dev-dependencies]
rand = "0.7"
