name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
version: 0.3.2
#authors:
#- Alexander Schacht <grumpf@gmx.de>
#- Primaël Quémerais <primael@reefind.com>
#- Marcus Cantu
homepage: https://github.com/Grumpf86/openfoodfacts-dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  async_loader: ^0.1.2
  json_annotation: ^3.0.0
  http: ^0.12.0
  path: ^1.6.4
  image: ^2.1.4

dev_dependencies:
  test: any
  build_runner: ^1.6.9
  json_serializable: ^3.2.2


# https://www.dartlang.org/tools/pub/pubspec
flutter: