name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
version: 0.3.15+3
#authors:
#- Alexander Schacht <grumpf@gmx.de>
#- Primaël Quémerais <primael@reefind.com>
#- Marcus Cantu
#- Peter Tran-Jørgensen
#contributors:
#- Ilia (Elliot) Tikhomirov
#- Frédéric Julian
#- Mohamed Boussaid
#- monsieurtanuki
#- Stéphane Gigandet
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  json_annotation: ^3.1.1
  http: ^0.12.2
  path: ^1.7.0
  image: ^2.1.19

dev_dependencies:
  analyzer: ^0.41.2
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# https://www.dartlang.org/tools/pub/pubspec

