name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
version: 1.0.2-beta
#authors:
#- Alexander Schacht <grumpf@gmx.de>
#- Primaël Quémerais <primael@reefind.com>
#- Marcus Cantu
#- Peter Tran-Jørgensen
#contributors:
#- Ilia (Elliot) Tikhomirov
#- Frédéric Julian
#- Mohamed Boussaid
#- monsieurtanuki
#- Stéphane Gigandet
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  http: ^0.13.0
  path: ^1.8.0
  image: ^3.0.1

dev_dependencies:
  analyzer: ^1.1.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  pedantic: ^1.11.0
  test: ^1.16.8

# https://www.dartlang.org/tools/pub/pubspec

