service: serverless-shared
frameworkVersion: "3"

provider:
  name: aws

resources:
  Resources:
    JavaSharedEventBus:
      Type: AWS::Events::EventBus
      Properties: 
          Name: "JavaTracingEventBus"

    SharedEventBusNameParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /java/shared/event-bus-name
        Type: String
        Value: !Ref JavaSharedEventBus
