#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      nodeLayerVersion: "115"
      extensionLayerVersion: "62"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: datadoghq.eu
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: NodeProductApi
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 512
    Environment:
      Variables:
        ENV: !Ref Env
        DD_EXTENSION_VERSION: "next"
        DD_SERVERLESS_APPSEC_ENABLED: "true"
        TABLE_NAME: !Ref ProductApiTable
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
    Architectures:
      - x86_64

Resources:
  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: getProductFunction.handler
      FunctionName: !Sub GetProductFunction-${Env}
      Events:
        GetProduct:
          Type: HttpApi
          Properties: 
            Path: /product/{productId}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref ProductApiTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
              
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: createProductFunction.handler
      FunctionName: !Sub CreateProductFunction-${Env}
      Events:
        GetProduct:
          Type: HttpApi
          Properties: 
            Path: /product
            Method: post
      Environment:
        Variables:
          PRODUCT_CREATED_TOPIC_ARN: !Ref ProductCreatedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductCreatedTopic.TopicName
            
  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: updateProductFunction.handler
      FunctionName: !Sub UpdateProductFunction-${Env}
      Events:
        GetProduct:
          Type: HttpApi
          Properties: 
            Path: /product
            Method: put
      Environment:
        Variables:
          PRODUCT_UPDATED_TOPIC_ARN: !Ref ProductUpdatedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductUpdatedTopic.TopicName
            
  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: deleteProductFunction.handler
      FunctionName: !Sub DeleteProductFunction-${Env}
      Events:
        GetProduct:
          Type: HttpApi
          Properties: 
            Path: /product/{productId}
            Method: delete
      Environment:
        Variables:
          PRODUCT_DELETED_TOPIC_ARN: !Ref ProductDeletedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductDeletedTopic.TopicName
  
  ProductCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductCreatedTopic-${Env}"
  ProductUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductUpdatedTopic-${Env}"
  ProductDeletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductDeletedTopic-${Env}"
  
  ProductCreatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-created-topic
      Type: String
      Value: !Ref ProductCreatedTopic
  ProductUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-updated-topic
      Type: String
      Value: !Ref ProductUpdatedTopic
  ProductDeletedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-deleted-topic
      Type: String
      Value: !Ref ProductDeletedTopic
  ProductApiTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-table-name
      Type: String
      Value: !Ref ProductApiTable

  ProductApiTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub NodeProducts-${Env}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

  ApiEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/api-endpoint
      Type: String
      Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

Outputs:
  NodeProductApiEndpoint:
    Description: Product API Endpoint
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: NodeProductApiEndpoint