name: 'Helm catalog'
description: 'helm install service catalog to `catalog` namespace'
inputs:
  kube_config_data:
    description: "kubeconfig"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kube_config_data }}
