name: 'Create service instance'
description: 'Create service instance'
inputs:
  kube_config_data:
    description: "kubeconfig"
    required: true
  namespace:
    description: "namespace name"
    required: false
  service:
    description: "desired service name"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kube_config_data }}
    - ${{ inputs.namespace }}
    - ${{ inputs.service }}