name: Publish-Crate-Upon-Release
on:
  release:
    types: [published]

jobs:
  publish-automatically:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      -  uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
         with:
           toolchain: stable
           override: true

      - name: publish crates
        run: cargo publish --token ${{ secrets.CARGO_API_TOKEN }}
