name: 'Build'
on:
  - 'push'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Setup .NET Core SDK'
        uses: 'actions/setup-dotnet@v3'
        with:
          dotnet-version: '7.0.x'
      - name: 'Build'
        run: 'dotnet build DirectMusic -c Release -o __build && dotnet pack -c Release -o ./__publish/ -v detailed DirectMusic'
      - name: 'Publish'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'NuGet Package'
          path: '__publish'
      - name: 'Copy Artifacts'
        run: > 
          mkdir Artifacts && mv DirectMusic/runtimes Artifacts/ &&
          cp __build/DirectMusic.dll Artifacts/ &&
          cp __build/DirectMusic.pdb Artifacts/ &&
          echo "Copy the native library for your OS from the `runtime` folder into the same folder `DirectMusic.dll` is in." > Artifacts/README.md
      - name: 'Publish'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'Managed DLL'
          path: 'Artifacts'
