name: "Build Artifacts"

on: workflow_dispatch

jobs:
  build-lib:
    name: Build Library

    strategy:
      matrix:
        include:
          - os: macos-latest
            lib: libaries_askar.dylib
          - os: windows-latest
            lib: aries_askar.dll

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check Cargo.lock
        run: cargo generate-lockfile --locked

      - name: Restore dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}

      - name: Build library
        run: cargo build --release --locked

      - name: Upload library artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library-${{ runner.os }}
          path: target/release/${{ matrix.lib }}

  build-py:
    name: Build Python
    needs: build-lib

    strategy:
      matrix:
        include:
          - os: macos-latest
            plat-name: macosx_10_9_x86_64
            python-version: 3.6
          - os: windows-latest
            plat-name: win32
            python-version: 3.6

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Fetch library artifacts
        uses: actions/download-artifact@v2
        with:
          name: library-${{ runner.os }}
          path: wrappers/python/aries_askar/

      - name: Build python packages
        run: |
          python setup.py bdist_wheel
        working-directory: wrappers/python

      - name: Upload python artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-${{ runner.os }}
          path: wrappers/python/dist/*
