name: Build docker images

on:
  workflow_run:
    workflows: ["Repo Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [ 
          {arch: 'linux/amd64', tag: 'develop'},
          {arch: 'linux/arm64', tag: 'develop-arm64'}]
        container: [
          {name: 'aio-apache', context: './Containers/apache'},
          {name: 'aio-borgbackup', context: './Containers/borgbackup'},
          {name: 'aio-collabora', context: './Containers/collabora'},
          {name: 'aio-domaincheck', context: './Containers/domaincheck'},
          {name: 'all-in-one', context: './Containers/mastercontainer'},
          {name: 'aio-nextcloud', context: './Containers/nextcloud'},
          {name: 'aio-postgresql', context: './Containers/postgresql'},
          {name: 'aio-redis', context: './Containers/redis'},
          {name: 'aio-talk', context: './Containers/talk'},
          {name: 'aio-watchtower', context: './Containers/watchtower'},
          {name: 'aio-clamav', context: './Containers/clamav'},
          {name: 'aio-onlyoffice', context: './Containers/onlyoffice'}]
        exclude:
          - platform: {arch: 'linux/arm64', tag: 'develop-arm64'}
            container: {name: 'aio-clamav', context: './Containers/clamav'}
          - platform: {arch: 'linux/arm64', tag: 'develop-arm64'}
            container: {name: 'aio-onlyoffice', context: './Containers/onlyoffice'}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            nextcloud/${{ matrix.container.name }}
          tags: |
            ${{ matrix.platform.tag }}

      - name: Build docker image and push to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.container.context }}
          platforms: ${{matrix.platform.arch}}
          no-cache: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
