name: Clean up

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Delete old tags
        run: |
          REPOSITORY=stand-with-ukraine
          LEAVE_LAST=10
          TAGS=$(doctl registry repository lt $REPOSITORY --format Tag,UpdatedAt | tail -n +2 | sort -rk2 | awk '{print $REPOSITORY}' | grep -v latest | tail -n +$LEAVE_LAST | tr '\n' ' ')
          [[ -n $TAGS ]] && doctl registry repository dt $REPOSITORY $TAGS --force
          echo Tags removed: $TAGS

      - name: Clean up garbage
        run: |
          doctl registry garbage-collection start registry.digitalocean.com/stand-with-ukraine --include-untagged-manifests --force
