name: .NET Test

on:
    push:
      paths:
        - src/dotnet/**
    workflow_dispatch:
    pull_request:
      types: [opened]
      paths:
        - src/dotnet/**

permissions:
  id-token: write
  contents: read

jobs:
  clean-and-package:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      -
        name: dotnet test
        shell: bash
        run: |
          make test-dotnet