name: Create Imaginary Container

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * 1'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Create Imaginary Container

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        run: |
          git clone https://github.com/h2non/imaginary.git

      - name: Build and push image
        run: |
          cd imaginary

          # Fix the build based on https://github.com/h2non/imaginary/issues/387
          sed -i 's|github.com/h2non/bimg v1.1.4|github.com/h2non/bimg v1.1.7|' go.mod
          sed -i 's|^RUN go mod download$|RUN go mod tidy && go mod download|' Dockerfile

          # Build the image
          DATE="$(date +"%Y%m%d_%H%M%S")"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name builder --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx build --platform=linux/arm64,linux/amd64 . --file Dockerfile --tag nextcloud/imaginary --push --label "${DATE}"
