name: Java Package

on:
    push:
      branches:
        - main
      paths:
        - src/java/**
    workflow_dispatch:
    pull_request:
      types: [opened]
      paths:
        - src/java/**

permissions:
  id-token: write
  contents: read

jobs:
  clean-and-package:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
      -
        name: Maven build
        shell: bash
        run: |
          cd src/java/
          mvn clean package