#demo: install service catalog using Helm

on:
  workflow_dispatch:

name: K8s Demo.

jobs:
  k8s-demo-catalog:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: install service catalog
        uses: ./.github/actions/k8s-helm-catalog
        with:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}