#demo: Clean k8s namespace

on:
  workflow_dispatch:
    input:
      namespace:
        description: "k8s Namespace"
        required: false
      service_name: 
        description: "Service instance name"
        required: false

name: K8s Demo. Clean

jobs:
  k8s-demo-clean: 
    name: Clean K8s
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: clean
        uses: ./.github/actions/k8s-demo-clean
        with:
          NAMESPACE: ${{ github.event.inputs.namespace }}
          SERVICE: ${{ github.event.inputs.service_name }}
          atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
          atlas_org_id: ${{ secrets.ATLAS_ORG_ID }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
