#demo: Deploy test application

on:
  workflow_dispatch:
    input:
      namespace:
        description: "k8s Namespace"
        required: false
      service_name:
        description: "Service instance name"
        required: false

name: K8s Demo. Deploy test application

jobs:
  k8s-demo-test:
    name: Deploy test application
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy test application
        uses: ./.github/actions/k8s-demo-test-app
        with:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
          SERVICE: ${{ github.event.inputs.service_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
