name: Promote to latest

on:
  workflow_dispatch:

jobs:
  get_time:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.date.outputs.date }}
    steps:
      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +"%Y%m%d_%H%M%S")"

  promote_to_latest:
    needs: get_time
    runs-on: ubuntu-latest
    name: Promote from beta to latest 
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          'aio-apache',
          'aio-borgbackup',
          'aio-collabora',
          'aio-domaincheck',
          'all-in-one',
          'aio-nextcloud',
          'aio-postgresql',
          'aio-redis',
          'aio-talk',
          'aio-watchtower',
          'aio-clamav',
          'aio-onlyoffice',
          'aio-imaginary',
          'aio-fulltextsearch']

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Promote images from beta to latest
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        DATE="${{needs.get_time.outputs.output1}}"
        set +x
        # x64
        docker pull nextcloud/$AIO_NAME\:beta
        docker tag nextcloud/$AIO_NAME\:beta nextcloud/$AIO_NAME\:latest
        docker push nextcloud/$AIO_NAME\:latest
        docker tag nextcloud/$AIO_NAME\:beta nextcloud/$AIO_NAME\:"$DATE"-latest
        docker push nextcloud/$AIO_NAME\:"$DATE"-latest
        if [ "$AIO_NAME" = "aio-nextcloud" ]; then
          set -x
          PHP_VERSION="$(docker inspect nextcloud/aio-nextcloud:beta | grep PHP_VERSION | grep -oP '[0-8.]+' | sed 's|\.[0-9]\+$||')"
          if [ -n "$PHP_VERSION" ]; then
            docker tag nextcloud/aio-nextcloud\:beta nextcloud/aio-nextcloud\:php"$PHP_VERSION"-latest
            docker push nextcloud/aio-nextcloud\:php"$PHP_VERSION"-latest
          fi
          set +x
        fi
        if [ "$AIO_NAME" != "aio-clamav" ]; then
          # arm64 
          docker pull nextcloud/$AIO_NAME\:beta-arm64
          docker tag nextcloud/$AIO_NAME\:beta-arm64 nextcloud/$AIO_NAME\:latest-arm64
          docker push nextcloud/$AIO_NAME\:latest-arm64
          docker tag nextcloud/$AIO_NAME\:beta-arm64 nextcloud/$AIO_NAME\:"$DATE"-latest-arm64
          docker push nextcloud/$AIO_NAME\:"$DATE"-latest-arm64
          if [ "$AIO_NAME" = "aio-nextcloud" ]; then
          set -x
          PHP_VERSION="$(docker inspect nextcloud/aio-nextcloud:beta-arm64 | grep PHP_VERSION | grep -oP '[0-8.]+' | sed 's|\.[0-9]\+$||')"
          if [ -n "$PHP_VERSION" ]; then
            docker tag nextcloud/aio-nextcloud\:beta-arm64 nextcloud/aio-nextcloud\:php"$PHP_VERSION"-latest-arm64
            docker push nextcloud/aio-nextcloud\:php"$PHP_VERSION"-latest-arm64
          fi
          set +x
        fi
        fi
