name: Promote to beta

on:
  workflow_dispatch:

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote from develop to beta 
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          'aio-apache',
          'aio-borgbackup',
          'aio-collabora',
          'aio-domaincheck',
          'all-in-one',
          'aio-nextcloud',
          'aio-postgresql',
          'aio-redis',
          'aio-talk',
          'aio-watchtower',
          'aio-clamav',
          'aio-onlyoffice',
          'aio-imaginary',
          'aio-fulltextsearch']

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Promote images from develop to beta (create multiarch)
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        set +x
        
        if [ "$AIO_NAME" != "aio-clamav" ]; then
            # create multiarch image
            docker manifest create nextcloud/$AIO_NAME\:beta -a nextcloud/$AIO_NAME\:develop -a nextcloud/$AIO_NAME\:develop-arm64
            docker manifest push nextcloud/$AIO_NAME\:beta
            
            # arm64
            docker manifest create nextcloud/$AIO_NAME\:beta-arm64 -a nextcloud/$AIO_NAME\:develop-arm64
            docker manifest push nextcloud/$AIO_NAME\:beta-arm64
            
        else
            # amd64
            docker buildx imagetools create --tag nextcloud/$AIO_NAME\:beta nextcloud/$AIO_NAME\:develop
        fi
