name: Promote to latest

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: "Name of the container image - See https://github.com/nextcloud-releases/all-in-one/blob/main/.github/workflows/build_images.yml#L21-L30 for available names. Please verify before running this workflow that no job is running here: https://github.com/nextcloud-releases/all-in-one/actions/workflows/build_images.yml"
        required: true

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote ${{ github.event.inputs.imageName }} from develop to latest 
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Promote image to Docker Hub
      run: |
        AIO_NAME=${{ github.event.inputs.imageName }}
        # x64
        docker pull nextcloud/$AIO_NAME\:develop
        docker tag nextcloud/$AIO_NAME\:develop nextcloud/$AIO_NAME\:latest
        docker push nextcloud/$AIO_NAME\:latest
        # arm64 
        docker pull nextcloud/$AIO_NAME\:develop-arm64
        docker tag nextcloud/$AIO_NAME\:develop-arm64 nextcloud/$AIO_NAME\:latest-arm64
        docker push nextcloud/$AIO_NAME\:latest-arm64
