name: "Run Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-deps:
    name: Cache Dependencies

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Cargo.lock
        run: cargo generate-lockfile --offline --locked

      - name: Cargo cache dependencies
        id: cargo-deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}

      - name: Fetch dependencies
        if: ${{ steps.cargo-deps.outputs.cache-hit != 'true' }}
        run: cargo fetch --locked

  test:
    name: Test

    needs: cache-deps

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Restore dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}

      - name: Cargo check
        run: cargo check --locked

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Debug build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --locked

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
