---
jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
        with:
          days-before-close: 5
          days-before-stale: 30
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  issues: read
  pull-requests: write
