name: test-sdk

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Chekout code
      uses: actions/checkout@v2

    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - run: flutter pub get

    - name: Check for formatting issues (run "flutter format . ")
      run: flutter format --set-exit-if-changed .

    - run: flutter analyze

    - run: flutter test test/
