name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.17, 1.18 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Install docker-compose v2
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          gh release -R docker/compose download -p docker-compose-linux-x86_64
          mv -f docker-compose-linux-x86_64 docker-compose
          sudo mv /usr/local/bin/docker-compose /usr/local/bin/docker-compose-v2
          sudo install docker-compose /usr/local/bin/
          docker-compose --version

      - run: task test
