name: test-sdk

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.x'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test test/
